### PR TITLE
SLING-11917 Evaluate constructor parameter names via reflection

### PR DESCRIPTION
**Pull request by kwin**
This is available if compiled accordingly (with javac option `-parameters`, https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html#option-parameters), supported since javac 8+

### CODE REVIEW

**Comment by stefanseifert** [comment]
can you add a test case evaluating the new behavior?

i've never used the `-parameters` option, if i understand correctly it's still optional and not activated by default. so we need probably multiple maven verify executions or separate integration tests that test our code with variants of this flag enabled and not enabled, to ensure it works as expected in all conditions?

**Comment by kwin** [comment]
The API https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Parameter.html is available since Java 8 (no matter if `-parameters` is used or not). The only difference is that https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Parameter.html#isNamePresent-- returns `false` by default and https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Parameter.html#getName-- returns an artificial name by default. But I will look into adding ITs (the current ones proof though that everything works by default, i.e. without using --parameters, so only ones with --parameters are currently not existing).

**Comment by henrykuijpers** [comment]
Wouldn't that be as simple as adding another compile step in the project, for a separate source folder, that will have a sling model available to test?

**Comment by kwin** [comment]
@henrykuijpers Yes, but I tried to do https://github.com/apache/sling-org-apache-sling-models-impl/pull/46 first, which turned out to be more complex.

**Review by stefanseifert — APPROVED** [review]
this is especially useful in combination with #51 for record classes
i'm fine with applying it also without the IT to not block this here any further - we can add the ITs later.

**Pull request merged**
