### PR TITLE
SLING-7586 - using weak references as cache values to avoid memory leak

### PR DESCRIPTION
**Pull request by justinedelson**

### CODE REVIEW

**Comment by paul-bjorkstrand** [comment]
Not sure if this is the best approach. If the leak is related to the `adaptableCache`'s keys (classes) being strongly referenced, then the `adaptableCache` items (the values of the outer map, or `adapterCache`) should be [WeakHashMaps](https://docs.oracle.com/javase/8/docs/api/java/util/WeakHashMap.html), rather than having the result of the adaptation be kept in [WeakReferences](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/WeakReference.html).

Actually, thinking about how Felix (and any OSGi container) loads classes, that is probably the way to do it. If a class is collected, because its bundle was reloaded/reinstalled, then the old class (before the reload) is not capable of being collected by the GC, because they are strongly referenced by being the keys in the inner map.

This PR has two issues, as far as I can see:

1. It does not resolve the memory leak issue, since the keys of the inner maps (the adaptableCache) are still strongly referenced by the map itself.
2. it adds an odd behavior/performance regression: the adaptableCache maps will have keys for given classes, but will have no values, as the model instances may have been (and likely will have been) collected by the GC, since they are weakly referenced, due to being put inside WeakReferences.

The field should still be typed as
```
Map<Object, Map<Class<?>, Object>> adapterCache;
```
and initialized by 
```
adapterCache = Collections.synchronizedMap(new WeakHashMap<>());
```

The values of the `adapterCache` should by typed as
```
Map<Class<?>, Object> adaptableCache;
```
and initialized by
```
adaptableCache = Collections.synchronizedMap(new WeakHashMap<>(INNER_CACHE_INITIAL_CAPACITY));
```

**Comment by paul-bjorkstrand** [comment]
@justinedelson , after seeing https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/177 I believe we need a combination of your approach, using `WeakReference` to solve the issue of indirect self referencing, and the addition of using `WeakHashMap` for the inner `Map` instances to completely solve the issue.

When I first looked through the code above, I was unable to see the type of issue you were trying to solve. Reading that other ticket on asset-share-commons (and running into the issue in my environment) gave me a clearer understanding of the full issue..

**Comment by klcodanr** [comment]
@paul-bjorkstrand I have some cycles to help with this. Let's work together on coming up with some way to test the efficacy of this change.

**Comment by klcodanr** [comment]
Fixed with #9

**Pull request closed without merging**
