### PR TITLE
upgrade maven-shade-plugin

### PR DESCRIPTION
**Pull request by hboutemy**
required to fix Reproducible Builds issues: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/sling/org.apache.sling.models.impl/README.md

### CODE REVIEW

**Review by rombert — COMMENTED** [review]
Thanks for the PR @hboutemy . If I understand correctly, we can also upgrade to the latest ASF parent pom ( https://github.com/apache/sling-parent/pull/46 ) and then upgrade the parent pom for this bundle.

This seems to work for me with a SNAPSHOT parent build

```
[INFO] --- artifact:3.5.3:compare (default-cli) @ org.apache.sling.models.impl ---
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-util/1.9.20/maven-resolver-util-1.9.20.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-util/1.9.20/maven-resolver-util-1.9.20.pom (2.9 kB at 68 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver/1.9.20/maven-resolver-1.9.20.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver/1.9.20/maven-resolver-1.9.20.pom (22 kB at 548 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-api/1.9.20/maven-resolver-api-1.9.20.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-api/1.9.20/maven-resolver-api-1.9.20.pom (2.7 kB at 69 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-util/1.9.20/maven-resolver-util-1.9.20.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-util/1.9.20/maven-resolver-util-1.9.20.jar (196 kB at 2.3 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-api/1.9.20/maven-resolver-api-1.9.20.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-api/1.9.20/maven-resolver-api-1.9.20.jar (157 kB at 3.4 MB/s)
[WARNING] SCM source tag in buildinfo source.scm.tag=org.apache.sling.models.impl-1.7.2 does not permit rebuilders reproducible source checkout
[INFO] Saved info on build to /home/robert/sources/apache/sling/org-apache-sling-models-impl/target/org.apache.sling.models.impl-1.7.3-SNAPSHOT.buildinfo
[INFO] Checking against reference build from central...
[INFO] Reference buildinfo file not found: it will be generated from downloaded reference artifacts
[INFO] Reference build java.version: 21 (from MANIFEST.MF Build-Jdk-Spec)
[INFO] Reference build os.name: Unix (from pom.properties newline)
[INFO] Minimal buildinfo generated from downloaded artifacts: /home/robert/sources/apache/sling/org-apache-sling-models-impl/target/reference/org.apache.sling.models.impl-1.7.3-SNAPSHOT.buildinfo
[INFO] Reproducible Build output summary: 3 files ok
[INFO] Reproducible Build output comparison saved to /home/robert/sources/apache/sling/org-apache-sling-models-impl/target/org.apache.sling.models.impl-1.7.3-SNAPSHOT.buildcompare
```

Would that work for you?

**Comment by hboutemy** [comment]
yes, that's another way to solve the issue

**Comment by rombert** [comment]
@hboutemy - I'm closing this in favour of #59, which should have the same effect, only easier to port to other Sling modules.

Please let me know if that fix is not enough.

**Comment by hboutemy** [comment]
@rombert ASF parent upgrade is only ok in Sling parent 62 https://github.com/apache/sling-parent/pull/48

can you upgrade, please?

**Comment by rombert** [comment]
Sure @hboutemy - see https://github.com/apache/sling-org-apache-sling-models-impl/pull/62

**Pull request closed without merging**
